name:                little-rio
version:             0.1.0
github:              "githubuser/little-rio"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "(c) 2020 Author name here"

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/githubuser/little-rio#readme>

dependencies:
- base >= 4.12 && < 5

default-extensions:
  - ConstraintKinds
  - DataKinds
  - DeriveFunctor
  - DeriveFoldable
  - DeriveGeneric
  - DeriveTraversable
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NoImplicitPrelude
  - OverloadedStrings
  - Rank2Types
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fno-warn-unused-top-binds

library:
  source-dirs: src

executables:
  little-rio-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - little-rio

tests:
  little-rio-test:
    main:                Tasty.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - little-rio
    - tasty
    - tasty-discover
    - tasty-hunit
