name:                little-rio
version:             0.1.0
github:              "ejconlon/little-rio"
license:             BSD3
author:              "Eric Conlon"
maintainer:          "ejconlon@gmail.com"
copyright:           "(c) 2020 Eric Conlon"
category:            Control
synopsis:            When you need just the RIO monad

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/ejconlon/little-rio#readme>

dependencies:
- base >= 4.12 && < 5
- exceptions >= 0.10
- microlens >= 0.4
- microlens-mtl >= 0.2
- mtl >= 2.2
- unliftio-core >= 0.1

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fno-warn-unused-top-binds

library:
  source-dirs: src
